### ISSUE TITLE
[Mint]Can not copy the folder to ../plugins

### ISSUE THREAD

**Issue by Claus1** [wandenberg/rhythmbox-plugins#1]
First I do not have /.local but /usr and I don't have write access in /usr/lib/rhythmbox/plugins.

**Comment by wandenberg** [comment]
Hi @Claus1 be sure you are following the instruction here https://github.com/wandenberg/rhythmbox-plugins/tree/master/deletefile

The plugins folder must be created/exists at `~/.local/share/rhythmbox` . The `.local` is on the user home directory, not on  `/`.
